### ISSUE TITLE
libs missing, the folder libs is empty

### ISSUE THREAD

**Issue by BruceOuyang** [yangboz/verdant-octo-woof#1]
hey there, thanks for share this project.
I cloned and found a problem, the folder "libs" is empty, and the lib "hipi-2.1.0.jar" is MUST.
Cound you push these libs , thank you.

**Comment by yangboz** [comment]
@BruceOuyang sorry for missing files, and this project is under going, the FaceCount.xml ant file still need refactory,any  other issues?
